spring:
  datasource:
    url: jdbc:mysql:///xxx?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

scheduler:
  cron: 0,5 10,14,15 * * * *
  expiredDay: 30
  gotifyUrl: https://xxx.xxx.xxx/message?token=xxx
  enableCheck: false

xxl:
  job:
    enabled: true
    addresses: http://1.1.1.1:9001/xxl-job-admin
    appName: test
    accessToken: 123456
    address:
    ip:
    port: 9527
    logPath:
    logRetentionDays: 30

notify:
  gotify:
    enabled: true
    url: https://xxx.xxx.xxx/message?token=xxx
  email:
    enabled: true
    recipient: User
    host: xxx.xxx.xxx
    port: 465
    username: xxx@xxx.xxx
    from: xxx@xxx.xxx
    password: 123456
    smtpAuth: true
    socketFactoryClass: javax.net.ssl.SSLSocketFactory
    smtpStarttlsEnable: false
    defaultTo: xxx@xxx.xxx
    connectionTimeout: 10000
    timeout: 10000
    debug: false

mybatis-plus:
  global-config:
    banner: false
    db-config:
      #全局软删除配置
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-not-delete-value: false
      logic-delete-value: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
server:
  port: 8088
logging:
  level:
    com.vps.model.*.mapper: debug